#!/bin/bash
#SBATCH -p batch
#SBATCH -N 1
#SBATCH -n 2
#SBATCH --time=05:00:00
#SBATCH --mem=16GB

# Notification configuration 
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=brady.welsh@adelaide.edu.au

# Module load FastQC
# Execute the program

.fastqc -t 2 \
-o {path to Ouput Directory} {path to Input .fastq Files}
