#!/bin/bash
#SBATCH -p highmem
#SBATCH -N 1
#SBATCH -n 30
#SBATCH --time=16:00:00
#SBATCH --mem=480GB

# Notification configuration
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=brady.welsh@adelaide.edu.au

# Executing script

#module load malt

malt-build -i /fast/users/a1688124/malt/1_malt-build/1_FastAInput/oral_microbiome \
-d /fast/users/a1688124/malt/1_malt-build/2_Indices/HOMD_OralMicrobiome \
-a2taxonomy /fast/users/a1688124/malt/1_malt-build/1_FastAInput/nucl_acc2tax-Nov2018.abin \
--sequenceType DNA -t 30 -v
