#!/bin/bash
#SBATCH -p highmem
#SBATCH -N 1
#SBATCH -n 32 
#SBATCH --time=30:00:00
#SBATCH --mem=1500GB

# Notification configuration
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=brady.welsh@adelaide.edu.au

# Executing script

# module load malt

malt-run -i {path to input fastq files} \
-a {path to output directory} \
-ou {path to output directory} \
-at SemiGlobal -f Text -d {path to directory containing matrix} \
-mem load --mode BlastN -t 32 -v
